# Generated by Django 3.2.6 on 2021-09-18 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumevent',
            name='event_date_exception',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='rate_average',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
