# Generated by Django 3.2.6 on 2021-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210918_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumevent',
            name='event_date_exception',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
